### ISSUE TITLE
To Do | Roadmap

### ISSUE THREAD

**Issue by mscamargo** [mscamargo/revenda-herbie#2]
- [ ] Compress html output
- [ ] Compress assets output
- [ ] MY_Model with common methods
- [ ] MY_Controller
  - [ ] render method to load pages with a layout/template
  - [ ] method to return a formated json for ajax requests
- [ ] Auth module/library

_Things built on top of CodeIgniter should be coded from scratch using CodeIgniter resources, not using libraries or community packages. Packages that provide solutions out of the framework (like [phpdotenv](https://github.com/vlucas/phpdotenv) or [minify](https://github.com/matthiasmullie/minify)) can be used._
